# Generated by Django 5.2.3 on 2025-06-25 03:35

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ProcesamientoAnalisis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_procesamiento', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Fecha de Procesamiento')),
                ('archivo_aging', models.CharField(max_length=255, verbose_name='Archivo Aging')),
                ('archivo_pipeline', models.CharField(max_length=255, verbose_name='Archivo Pipeline')),
                ('archivo_oracle', models.CharField(max_length=255, verbose_name='Archivo Oracle')),
                ('total_registros_aging', models.IntegerField(default=0, verbose_name='Total Registros Aging')),
                ('total_registros_pipeline', models.IntegerField(default=0, verbose_name='Total Registros Pipeline')),
                ('total_registros_oracle', models.IntegerField(default=0, verbose_name='Total Registros Oracle')),
                ('registros_actualizados_pipeline', models.IntegerField(default=0, verbose_name='Actualizados con Pipeline')),
                ('registros_actualizados_oracle', models.IntegerField(default=0, verbose_name='Actualizados con Oracle')),
                ('registros_no_coincidentes', models.IntegerField(default=0, verbose_name='Sin Coincidencias')),
                ('archivo_resultado', models.CharField(blank=True, max_length=255, verbose_name='Archivo Resultado')),
                ('archivo_no_coincidentes', models.CharField(blank=True, max_length=255, verbose_name='Archivo No Coincidentes')),
                ('logs_procesamiento', models.TextField(blank=True, verbose_name='Logs del Procesamiento')),
                ('estado', models.CharField(choices=[('procesando', 'Procesando'), ('completado', 'Completado'), ('error', 'Error')], default='procesando', max_length=20, verbose_name='Estado')),
                ('tiempo_procesamiento', models.FloatField(blank=True, null=True, verbose_name='Tiempo (segundos)')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Usuario')),
            ],
            options={
                'verbose_name': 'Procesamiento de Análisis',
                'verbose_name_plural': 'Procesamientos de Análisis',
                'ordering': ['-fecha_procesamiento'],
            },
        ),
        migrations.CreateModel(
            name='LogProcesamiento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Timestamp')),
                ('nivel', models.CharField(choices=[('INFO', 'Info'), ('WARNING', 'Warning'), ('ERROR', 'Error'), ('SUCCESS', 'Success')], default='INFO', max_length=10, verbose_name='Nivel')),
                ('mensaje', models.TextField(verbose_name='Mensaje')),
                ('procesamiento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logs_detallados', to='analisis.procesamientoanalisis', verbose_name='Procesamiento')),
            ],
            options={
                'verbose_name': 'Log de Procesamiento',
                'verbose_name_plural': 'Logs de Procesamiento',
                'ordering': ['timestamp'],
            },
        ),
    ]
