# Generated by Django 5.2.3 on 2025-06-17 21:07

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, unique=True)),
                ('codigo', models.CharField(max_length=20, unique=True)),
                ('descripcion', models.TextField(blank=True)),
                ('activa', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Categoría',
                'verbose_name_plural': 'Categorías',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='EstatusPMO',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado', models.CharField(choices=[('PLANIFICACION', 'Planificación'), ('APROBADO', 'Aprobado'), ('EN_PROCESO', 'En Proceso'), ('PENDIENTE', 'Pendiente'), ('REVISION', 'En Revisión'), ('COMPLETADO', 'Completado'), ('CANCELADO', 'Cancelado'), ('SUSPENDIDO', 'Suspendido')], max_length=20, unique=True)),
                ('descripcion', models.TextField(blank=True)),
                ('color', models.CharField(default='#6c757d', help_text='Color hexadecimal para UI', max_length=7)),
                ('orden', models.PositiveIntegerField(default=0)),
                ('activo', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Estatus PMO',
                'verbose_name_plural': 'Estados PMO',
                'ordering': ['orden', 'estado'],
            },
        ),
        migrations.CreateModel(
            name='Fabrica',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, unique=True)),
                ('codigo', models.CharField(max_length=20, unique=True)),
                ('ubicacion', models.CharField(max_length=200)),
                ('activa', models.BooleanField(default=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('responsable', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Fábrica',
                'verbose_name_plural': 'Fábricas',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='Articulo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo_articulo', models.CharField(db_index=True, max_length=50, unique=True)),
                ('denominacion', models.CharField(max_length=200)),
                ('descripcion', models.TextField(blank=True)),
                ('area_responsable', models.CharField(blank=True, choices=[('SISTEMAS', 'Sistemas'), ('ADMINISTRACION', 'Administración'), ('CONTABILIDAD', 'Contabilidad'), ('RECURSOS_HUMANOS', 'Recursos Humanos'), ('VENTAS', 'Ventas'), ('MARKETING', 'Marketing'), ('OPERACIONES', 'Operaciones'), ('MANTENIMIENTO', 'Mantenimiento')], max_length=20)),
                ('año', models.PositiveIntegerField()),
                ('fecha_inicio', models.DateField(blank=True, null=True)),
                ('fecha_estimada_fin', models.DateField(blank=True, null=True)),
                ('fecha_real_fin', models.DateField(blank=True, null=True)),
                ('costo_estimado', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('costo_real', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('moneda', models.CharField(choices=[('MXN', 'Peso Mexicano'), ('USD', 'Dólar Americano'), ('EUR', 'Euro')], default='MXN', max_length=3)),
                ('codigo_interno', models.CharField(blank=True, max_length=100)),
                ('codigo_externo', models.CharField(blank=True, max_length=100)),
                ('codigo_proveedor', models.CharField(blank=True, max_length=100)),
                ('progreso_porcentaje', models.PositiveIntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)])),
                ('prioridad', models.CharField(choices=[('BAJA', 'Baja'), ('MEDIA', 'Media'), ('ALTA', 'Alta'), ('CRITICA', 'Crítica')], default='MEDIA', max_length=10)),
                ('activo', models.BooleanField(default=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('creado_por', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='articulos_creados', to=settings.AUTH_USER_MODEL)),
                ('responsable', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='articulos', to='inventario.categoria')),
                ('estatus_pmo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='articulos', to='inventario.estatuspmo')),
                ('fabrica', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='articulos', to='inventario.fabrica')),
            ],
            options={
                'verbose_name': 'Artículo',
                'verbose_name_plural': 'Artículos',
                'ordering': ['-fecha_actualizacion'],
            },
        ),
        migrations.CreateModel(
            name='ImportacionDatos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('archivo_original', models.CharField(max_length=255)),
                ('fecha_importacion', models.DateTimeField(auto_now_add=True)),
                ('total_registros', models.PositiveIntegerField(default=0)),
                ('registros_exitosos', models.PositiveIntegerField(default=0)),
                ('registros_fallidos', models.PositiveIntegerField(default=0)),
                ('log_errores', models.TextField(blank=True)),
                ('notas', models.TextField(blank=True)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Importación de Datos',
                'verbose_name_plural': 'Importaciones de Datos',
                'ordering': ['-fecha_importacion'],
            },
        ),
        migrations.CreateModel(
            name='SeguimientoPMO',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comentarios', models.TextField(blank=True)),
                ('adjuntos', models.FileField(blank=True, null=True, upload_to='seguimientos/')),
                ('fecha_cambio', models.DateTimeField(auto_now_add=True)),
                ('articulo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='seguimientos', to='inventario.articulo')),
                ('estatus_anterior', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='seguimientos_desde', to='inventario.estatuspmo')),
                ('estatus_nuevo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='seguimientos_hacia', to='inventario.estatuspmo')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Seguimiento PMO',
                'verbose_name_plural': 'Seguimientos PMO',
                'ordering': ['-fecha_cambio'],
            },
        ),
        migrations.AddIndex(
            model_name='articulo',
            index=models.Index(fields=['codigo_articulo'], name='inventario__codigo__0ac0fc_idx'),
        ),
        migrations.AddIndex(
            model_name='articulo',
            index=models.Index(fields=['fabrica', 'estatus_pmo'], name='inventario__fabrica_34cbd2_idx'),
        ),
        migrations.AddIndex(
            model_name='articulo',
            index=models.Index(fields=['año', 'activo'], name='inventario__año_1a9c9f_idx'),
        ),
    ]
