# Generated by Django 5.2.3 on 2025-06-17 22:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0001_initial'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='articulo',
            name='inventario__codigo__0ac0fc_idx',
        ),
        migrations.RemoveIndex(
            model_name='articulo',
            name='inventario__fabrica_34cbd2_idx',
        ),
        migrations.RemoveIndex(
            model_name='articulo',
            name='inventario__año_1a9c9f_idx',
        ),
        migrations.RenameField(
            model_name='articulo',
            old_name='codigo_externo',
            new_name='articulo',
        ),
        migrations.RenameField(
            model_name='articulo',
            old_name='codigo_interno',
            new_name='estatus_pmo_texto',
        ),
        migrations.RenameField(
            model_name='articulo',
            old_name='codigo_proveedor',
            new_name='fabrica_texto',
        ),
        migrations.RemoveField(
            model_name='articulo',
            name='activo',
        ),
        migrations.RemoveField(
            model_name='articulo',
            name='area_responsable',
        ),
        migrations.RemoveField(
            model_name='articulo',
            name='categoria',
        ),
        migrations.RemoveField(
            model_name='articulo',
            name='codigo_articulo',
        ),
        migrations.RemoveField(
            model_name='articulo',
            name='costo_estimado',
        ),
        migrations.RemoveField(
            model_name='articulo',
            name='costo_real',
        ),
        migrations.RemoveField(
            model_name='articulo',
            name='creado_por',
        ),
        migrations.RemoveField(
            model_name='articulo',
            name='denominacion',
        ),
        migrations.RemoveField(
            model_name='articulo',
            name='fecha_estimada_fin',
        ),
        migrations.RemoveField(
            model_name='articulo',
            name='fecha_inicio',
        ),
        migrations.RemoveField(
            model_name='articulo',
            name='fecha_real_fin',
        ),
        migrations.RemoveField(
            model_name='articulo',
            name='moneda',
        ),
        migrations.RemoveField(
            model_name='articulo',
            name='prioridad',
        ),
        migrations.RemoveField(
            model_name='articulo',
            name='progreso_porcentaje',
        ),
        migrations.RemoveField(
            model_name='articulo',
            name='responsable',
        ),
        migrations.AddField(
            model_name='articulo',
            name='avp',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='articulo',
            name='cantidad_embarcada',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='articulo',
            name='costo_mxn_existencias',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True),
        ),
        migrations.AddField(
            model_name='articulo',
            name='costo_salida_mxn',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True),
        ),
        migrations.AddField(
            model_name='articulo',
            name='costo_unitario_distribucion',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True),
        ),
        migrations.AddField(
            model_name='articulo',
            name='costo_usd_existencias',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True),
        ),
        migrations.AddField(
            model_name='articulo',
            name='existencia_actual',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='articulo',
            name='fecha_implementacion',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='articulo',
            name='historial',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='articulo',
            name='id_pmo',
            field=models.CharField(db_index=True, default='PMO-TEMP', max_length=100),
        ),
        migrations.AddField(
            model_name='articulo',
            name='nombre_proyecto',
            field=models.CharField(blank=True, max_length=300),
        ),
        migrations.AddField(
            model_name='articulo',
            name='nombre_proyecto_recibo',
            field=models.CharField(blank=True, max_length=300),
        ),
        migrations.AddField(
            model_name='articulo',
            name='observaciones',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='articulo',
            name='orden_compra',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='articulo',
            name='program_manager',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='articulo',
            name='proveedor',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='articulo',
            name='retrasos_salida',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='articulo',
            name='tipo',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='articulo',
            name='estatus_pmo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='articulos', to='inventario.estatuspmo'),
        ),
        migrations.AlterField(
            model_name='articulo',
            name='fabrica',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='articulos', to='inventario.fabrica'),
        ),
        migrations.AddIndex(
            model_name='articulo',
            index=models.Index(fields=['id_pmo'], name='inventario__id_pmo_5b49ed_idx'),
        ),
        migrations.AddIndex(
            model_name='articulo',
            index=models.Index(fields=['año'], name='inventario__año_225f93_idx'),
        ),
    ]
