# Generated by Django 5.2.3 on 2025-06-17 20:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PerfilUsuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('foto_perfil', models.ImageField(blank=True, null=True, upload_to='perfiles/')),
                ('telefono', models.CharField(blank=True, max_length=15, null=True)),
                ('area', models.CharField(blank=True, choices=[('SISTEMAS', 'Sistemas'), ('ADMINISTRACION', 'Administración'), ('CONTABILIDAD', 'Contabilidad'), ('RECURSOS_HUMANOS', 'Recursos Humanos'), ('VENTAS', 'Ventas'), ('MARKETING', 'Marketing'), ('OPERACIONES', 'Operaciones'), ('MANTENIMIENTO', 'Mantenimiento')], max_length=20, null=True)),
                ('puesto', models.CharField(blank=True, max_length=100, null=True)),
                ('fecha_ingreso', models.DateField(blank=True, null=True)),
                ('activo', models.BooleanField(default=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Perfil de Usuario',
                'verbose_name_plural': 'Perfiles de Usuarios',
                'ordering': ['usuario__first_name', 'usuario__last_name'],
            },
        ),
    ]
